// CSS variables are the source of truth; these aliases are safe for React styles.
export const designSystem = {
  colors: {
    background: 'var(--color-bg)',
    backgroundAlt: 'var(--color-bg-alt)',
    surface: 'var(--color-surface)',
    surfaceSoft: 'var(--color-surface-soft)',
    text: 'var(--color-text)',
    textStrong: 'var(--color-text-strong)',
    textDark: 'var(--color-text-dark)',
    muted: 'var(--color-muted)',
    border: 'var(--color-border)',
    borderDark: 'var(--color-border-dark)',
    accent: 'var(--color-accent)',
    accentSecondary: 'var(--color-accent-2)',
    accentTertiary: 'var(--color-accent-3)',
    highlight: 'var(--color-highlight)',
    panel: 'var(--color-panel)',
    button: 'var(--color-button)',
    buttonText: 'var(--color-button-text)',
    buttonHover: 'var(--color-button-hover)',
    buttonActive: 'var(--color-button-active)',
    buttonFocus: 'var(--color-button-focus)',
  },
  gradients: {
    heroText: 'var(--gradient-hero-text)',
    button: 'var(--gradient-button)',
    buttonHover: 'var(--gradient-button-hover)',
    panel: 'var(--gradient-panel)',
    glow: 'var(--gradient-glow)',
  },
  radii: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
  },
  shadows: {
    soft: 'var(--shadow-soft)',
    button: 'var(--shadow-button)',
    buttonHover: 'var(--shadow-button-hover)',
    card: 'var(--shadow-card)',
  },
  layout: {
    gutter: 'var(--gutter)',
    contentWidth: 'var(--content-width)',
    sectionSpace: 'var(--section-space)',
    gap: 'var(--grid-gap)',
  },
  typography: {
    hero: 'var(--text-hero)',
    section: 'var(--text-section)',
    body: 'var(--text-body)',
    service: 'var(--text-service)',
    number: 'var(--text-number)',
    price: 'var(--text-price)',
    contact: 'var(--text-contact)',
  },
  motion: {
    fast: 'var(--duration-fast)',
    reveal: 'var(--duration-reveal)',
    ease: 'var(--ease-standard)',
  },
} as const;

export const designTokens = {
  sectionShell: 'section-shell',
  sectionPadding: 'section-spacing',
  container: 'content-container',
  button: 'button',
} as const;
